# === ORTAK AYARLAR ===
spring:
  jpa:
    hibernate:
      ddl-auto: update    
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  profiles:
    active: dev

app:
  log-cleanup:
    cron: "0 0 2 * * *"

logging:
  level:
    org.springframework.web: INFO
    com.hoaxify: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# === DEV PROFİL ===
---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:C:/Users/GTUSR0728/test;IFEXISTS=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

hoaxify:
  upload-path: storage-dev


# === UAT PROFİL ===
---
spring:
  datasource:
    url: postgresql://postgres:UoVpTQNzotdsHfyDmWfFKmwUUokVSPsp@postgres.railway.internal:5432/railway
    driver-class-name: org.postgresql.Driver
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


hoaxify:
  upload-path: storage-uat

# === PRODUCTION PROFİL ===
---
spring:
  datasource:
    url: postgresql://postgres:HEDSPjZFUptTBtnbXajdXFFvEKGeAYzM@postgres.railway.internal:5432/railway
    driver-class-name: org.postgresql.Driver
    username: 
    password: 
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


hoaxify:
  upload-path: storage-production



