# === ORTAK AYARLAR ===
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  profiles:
    active: dev
  messages:
    basename: ValidationMessages
    encoding: UTF-8

app:
  log-cleanup:
    cron: "0 20 15 * * *"

logging:
  level:
    org.springframework.web: INFO
    com.hoaxify: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# === DEV PROFİL ===
---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./data/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

hoaxify:
  upload-path: storage-dev

# === UAT PROFİL ===
---
spring:
  config:
    activate:
      on-profile: uat
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: ValidationMessages
    encoding: UTF-8

logging:
  level:
    org.springframework.web: DEBUG
    com.hoaxify: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

hoaxify:
  upload-path: storage-uat

# === PRODUCTION PROFİL (2. madde EKLENDİ) ===
---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: ValidationMessages
    encoding: UTF-8

# >>> 2. madde: gerçek hatayı görmek için GEÇİCİ teşhis ayarları
server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: ALWAYS   # Teşhis bitince 'never' yap

logging:
  level:
    org.springframework.web: DEBUG
    com.hoaxify: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    # JSON yazımı ve MVC response konverterleri için detay log
    org.springframework.http.converter.json: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: DEBUG
    com.fasterxml.jackson.databind: DEBUG

hoaxify:
  upload-path: storage-production
