# === ORTAK AYARLAR ===
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  profiles:
    active: dev
  messages:
    basename: ValidationMessages
    encoding: UTF-8
  servlet:
    multipart:
      enabled: true
      max-file-size: 6MB
      max-request-size: 6MB

STORAGE_DIR_PATH: "C:/Eren/wsSpringApp/ws/storage-dev" 


app:
  log-cleanup:
    cron: "0 20 15 * * *"

logging:
  level:
    org.springframework.web: INFO
    com.hoaxify: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# === DEV PROFİL ===
---
spring:
  config:
    activate:
      on-profile: dev
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:file:./data/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

hoaxify:
  upload-path: storage-dev

# === PRODUCTION PROFİL ===
---
spring:
  config:
    activate:
      on-profile: production
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa: 
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  messages:
    basename: ValidationMessages
    encoding: UTF-8

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: ALWAYS

hoaxify:
  upload-path: /data/uploads
